version: "3.8"

services:

  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentex
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentex
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 #Debug
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local